using System.Security.Cryptography;
using System.Text.Json;
using FolderLens.Contracts;
using ImageMagick;
using VImage=NetVips.Image;

namespace FolderLens.Media.Worker;

internal static class CapabilityProbe
{
    private static readonly string[] formats=["jpeg","png","gif","webp","apng","bmp","tiff","ico","heic","avif","jxl"];
    public static async Task<RuntimeCapabilities> Read(string directory,CancellationToken token)
    {
        var results=new List<FormatRuntimeCapability>();string health=Path.Combine(AppContext.BaseDirectory,"health");
        foreach(string format in formats)
        {
            token.ThrowIfCancellationRequested();string provider=format is "bmp" or "ico" or "heic" or "jxl"?"Magick.NET":format=="apng"?"libvips + FFmpeg":"NetVips / libvips";
            bool available=format switch
            {
                "bmp" or "ico" or "heic" or "jxl"=>MagickNET.SupportedFormats.Any(f=>f.Format.ToString().Equals(format,StringComparison.OrdinalIgnoreCase)&&f.SupportsReading),
                "apng"=>NetVips.NetVips.TypeFind("VipsOperation","pngload")!=IntPtr.Zero&&File.Exists(AnimationFrameRenderer.FfmpegExecutable()),
                _=>NetVips.NetVips.TypeFind("VipsOperation",format switch{"avif"=>"heifload",_=>format+"load"})!=IntPtr.Zero
            };
            string input=Path.Combine(health,"sample."+format),output=Path.Combine(directory,"capability-"+format+".png");string? hash=null;
            try
            {
                if(!File.Exists(input)){results.Add(new(format,provider,available,"NOT_RUN",null,"MissingHealthFixture"));continue;}
                hash=Convert.ToHexString(SHA256.HashData(await File.ReadAllBytesAsync(input,token)));
                using var decoder=new StaticDecoder(input);decoder.Render(output,16,16);using(var fit=VImage.NewFromFile(output))if(fit.Width<1||fit.Height<1||fit.Width>16||fit.Height>16)throw new InvalidDataException("Invalid fit dimensions.");
                decoder.Render(output,1024,1024,true);using(var full=VImage.NewFromFile(output))if(full.Width!=Math.Min(1024,decoder.Width)||full.Height!=Math.Min(1024,decoder.Height))throw new InvalidDataException("Invalid full dimensions.");
                if(decoder.Animated)
                {
                    using var animation=new AnimationDecoder(input,16,16,decoder.Format);await animation.Next(output,token);await animation.Next(output,token);
                    await AnimationFrameRenderer.RenderTile(input,decoder.Format,decoder.Width,decoder.Height,new(FrameIndex:1),output,token);
                }
                results.Add(new(format,provider,available,"PASS",hash,null));
            }
            catch(OperationCanceledException){throw;}
            catch(Exception ex){results.Add(new(format,provider,available,"FAIL",hash,ex is DllNotFoundException or EntryPointNotFoundException?"DependencyUnavailable":ex.GetType().Name));}
            finally{if(File.Exists(output))File.Delete(output);}
        }
        int? abi=null;string? rawError=null;try{abi=checked((int)RawDecoder.Abi());if(abi!=1)rawError="AbiMismatch";}catch(Exception ex){rawError=ex.GetType().Name;}
        foreach(string format in new[]{"arw","dng","cr2","cr3","nef","raf","rw2","orf","pef"})results.Add(new(format,"LibRaw / RawBridge",abi==1,"NOT_RUN",null,rawError));
        return new(WorkerProtocol.BuildId,$"{NetVips.NetVips.Version(0)}.{NetVips.NetVips.Version(1)}.{NetVips.NetVips.Version(2)}",MagickNET.Version,abi,DateTimeOffset.UtcNow,results);
    }
    public static void GenerateFixtures(string directory)
    {
        Directory.CreateDirectory(directory);byte[] pixels=new byte[32*24*3];for(int i=0;i<pixels.Length;i++)pixels[i]=(byte)((i*17+i/96)%256);
        using var memory=VImage.NewFromMemory(pixels,32,24,3,NetVips.Enums.BandFormat.Uchar);using var srgb=memory.Copy(interpretation:NetVips.Enums.Interpretation.Srgb);byte[] png=srgb.WriteToBuffer(".png");
        foreach(string format in formats.Where(f=>f!="apng"))
        {
            var codec=Enum.Parse<MagickFormat>(format,true);
            if(!MagickNET.SupportedFormats.Any(f=>f.Format==codec&&f.SupportsWriting)){Console.WriteLine($"No fixture encoder: {format}");continue;}
            using var image=new MagickImage(png);image.Format=codec;image.Write(Path.Combine(directory,"sample."+format));
        }
        File.WriteAllText(Path.Combine(directory,"README.txt"),"Synthetic 32x24 diagnostic fixtures generated by FolderLens; animation fixtures are generated test patterns. These check basic component health, not full format compatibility.\n");
    }
}
